[project]
name = "blake3"
dynamic = ["version"]
requires-python = ">=3.8"

[build-system]
requires = ["maturin>=1.0,<2"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "numpy>=1.24.4",
    "pytest>=8.3.5",
]
